<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>LiteSkinViewer2D</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\LiteSkinViewer.Shared\LiteSkinViewer.Shared.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="SkiaSharp" Version="4.150.1" />
    </ItemGroup>
</Project>